FROM debian:buster

RUN apt-get update && apt-get install -y wget php-fpm vim \
		&& apt-get install -y mariadb-client \
		&& apt-get install -y php-mysqlnd php-mysqli

RUN wget https://wordpress.org/latest.tar.gz && \
		tar -xvf latest.tar.gz && \
		mkdir /var/www /var/www/html &&\
		mv /wordpress/* /var/www/html/ && \
		chown -R www-data:www-data /var/www/html && \
		rm -rf /wordpress latest.tar.gz

RUN mkdir /var/run/php

COPY www.conf /etc/php/7.3/fpm/pool.d/

# COPY /home/youskim/data/wp-config.php /var/www/html/

# RUN service php7.3-fpm start

CMD php-fpm7.3 --nodaemonize
