FROM debian:buster

RUN apt-get update && apt-get -y install mariadb-server vim

# RUN echo "bind-address = 0.0.0.0" > /etc/mysql/mariadb.conf.d/50-server.cnf

COPY 50-server.cnf /etc/mysql/mariadb.conf.d/

RUN service mysql start

# RUN mysql -e "CREATE DATABASE wordpress_db"; \
# 		mysql -e "CREATE USER 'youskim'@'%' IDENTIFIED BY 'dbtjd0513'"; \
# 		mysql -e "GRANT ALL ON wordpress_db.* TO 'youskim'@'%'"; \
# 		mysql -e "FLUSH PRIVILEGES";

 EXPOSE 3306

# ENTRYPOINT [ "mariadb" ]

CMD [ "mysqld"]
