version: '3'

volumes:
    db:
      name: db
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/youskim/data/mysql
    wp:
      name: wp
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/youskim/data/wordpress

services:
  nginx:
    # image: debian:buster
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile_nginx
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always

  wordpress:
    # image: debian:buster
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile_wordpress_php
    volumes:
      - wp:/var/www/html
    expose:
      - "9000"
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always

  mariadb:
    # image: debian:buster
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile_mariadb
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env
    expose:
      - "3306"
    networks:
      - inception
    restart: always

networks:
  inception:
    name: inception
    driver: bridge
